name: text_effect
version: 0.0.1
description: >
  To show text_effect
   - counter
   - expand and  rotate

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
