name: contact
description: >
  People can contact for N purpose
  gonna automate sending email

version: 0.0.1
homepage: none

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
