name: stackoverflow_stats

description: >
  To show stackOverflow stats; userInfo with 
   - contribution, rank and reputation

publish_to: none

version: 0.0.1
homepage: https://github.com/yeasin50/portfolio

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  html: ^0.15.5
  http: ^1.2.2

  effects:
    path: ../effects
  core:
    path: ../core

  text_effect:
    path: ../text_effect

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
