name: education
description: >
  A package to preview learning curve over lifeSpan. education

publish_to: none

version: 0.0.1
homepage: https://github.com/yeasin50/portfolio

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
