name: contact
resolution: workspace
description: >
  - A story to connect with me
  - gonna automate sending email

version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: ^3.11.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  effects:
    path: ../effects

  text_effect:
    path: ../text_effect

  core:
    path: ../core
  google_fonts: ^6.2.1
  flutter_bloc: any

  freezed_annotation: ^3.1.0
  json_annotation: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  json_serializable: ^6.7.1

