name: project
description: >
  Preview projects that I have been played so far

version: 0.0.1
repository: https://github.com/yeasin50/portfolio
publish_to: none

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
