{
  "sksl": {
    "entrypoint": "plasma_ball_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uSize;\nuniform float utime;\nuniform vec3 uPlasmaColor;\nuniform vec3 uBorderColor;\nuniform vec3 uCoreColor;\nuniform float uDense;\nuniform float uSpreed;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 uv = (FLT_flutter_local_FlutterFragCoord() / uSize) - vec2(0.5);\n    uv.x *= (uSize.x / uSize.y);\n    uv /= vec2(2.0);\n    float r = length(uv);\n    float time = utime;\n    vec2 fireUV = uv;\n    fireUV.y += (sin((time * 2.0) + (uv.x * 20.0)) * 0.0199999995529651641845703125);\n    fireUV.x += (sin((time * 1.5) + (uv.y * 20.0)) * 0.0199999995529651641845703125);\n    float fireR = length(fireUV);\n    float inner = 1.0 - smoothstep(uDense, uSpreed, fireR);\n    vec3 fireColor = mix(uPlasmaColor, uCoreColor, vec3(pow(1.0 - (fireR / 0.1500000059604644775390625), 2.0)));\n    vec3 innerColor = fireColor * inner;\n    float outer = smoothstep(0.100000001490116119384765625, 0.20000000298023223876953125, r) * (1.0 - smoothstep(0.20000000298023223876953125, 0.23000000417232513427734375, r));\n    vec3 outerColor = uBorderColor * outer;\n    float alpha = clamp(inner + outer, 0.0, 1.0);\n    vec3 col = innerColor + outerColor;\n    fragColor = vec4(col, alpha);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "utime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uPlasmaColor",
        "rows": 3,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "uBorderColor",
        "rows": 3,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 4,
        "name": "uCoreColor",
        "rows": 3,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 5,
        "name": "uDense",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 6,
        "name": "uSpreed",
        "rows": 1,
        "type": 10
      }
    ]
  }
}