name: portfolio_yeasin
description: >
  A new Flutter to create portfolio for 
  Me 🤭

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  core:
    path: ../../packages/core
  experience:
    path: ../../packages/experience

  stackoverflow_stats:
    path: ../../packages/stackoverflow_stats

  skill:
    path: ../../packages/skill

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/user_info.json
