name: core
resolution: workspace
description: A starting point for portfolio site.
version: 1.1.2
repository: https://github.com/yeasin50/portfolio
publish_to: none

environment:
  sdk: ^3.11.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0
  logger: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


