name: core
description: A starting point for portfolio site.
version: 1.0.0
repository: https://github.com/yeasin50/portfolio
publish_to: none

environment:
  sdk: ^3.0.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

dependencies:
  intl: ^0.19.0
